### Description : This notebook contains 2 methods with which we can load multiple images into an array using various python libraries

### Author name : Riya Chougule

### Date : 23/5/2020

### 1. Loading image using PIL 

In [73]:
from PIL import Image

In [74]:
import numpy as np

In [75]:
img1=Image.open('inv1.jpg')
img2=Image.open('inv2.jpg')
img3=Image.open('inv3.jpg')
img4=Image.open('inv4.jpg')

In [76]:
img1_array=np.array(img1)
img2_array=np.array(img2)
img3_array=np.array(img3)
img4_array=np.array(img4)

In [78]:
img1_array.shape

(747, 799, 3)

In [82]:
img2_array.shape

(747, 799, 3)

In [83]:
img3_array.shape

(648, 910, 3)

In [84]:
img4_array.shape

(678, 957, 3)

In [67]:
img1_array

array([[[161, 157, 156],
        [161, 157, 156],
        [161, 157, 156],
        ...,
        [ 80,  62,  50],
        [ 86,  68,  56],
        [ 80,  62,  50]],

       [[162, 158, 157],
        [162, 158, 157],
        [162, 158, 157],
        ...,
        [ 80,  62,  50],
        [ 85,  67,  55],
        [ 80,  62,  50]],

       [[164, 160, 159],
        [164, 160, 159],
        [163, 159, 158],
        ...,
        [ 80,  62,  50],
        [ 86,  68,  56],
        [ 80,  62,  50]],

       ...,

       [[134, 130, 129],
        [142, 138, 137],
        [154, 150, 149],
        ...,
        [112,  50,  51],
        [105,  43,  44],
        [101,  39,  40]],

       [[157, 153, 152],
        [141, 137, 136],
        [140, 136, 135],
        ...,
        [109,  51,  50],
        [100,  42,  41],
        [ 97,  39,  38]],

       [[152, 148, 147],
        [140, 136, 135],
        [134, 130, 129],
        ...,
        [108,  54,  52],
        [100,  46,  44],
        [ 98,  44,  42]]

In [68]:
img2_array

array([[[107, 105,  92],
        [106, 104,  91],
        [104, 102,  90],
        ...,
        [ 88,  84,  81],
        [ 83,  79,  76],
        [ 83,  79,  76]],

       [[106, 104,  91],
        [105, 103,  90],
        [104, 102,  90],
        ...,
        [ 83,  79,  76],
        [ 80,  76,  73],
        [ 83,  79,  76]],

       [[105, 103,  90],
        [104, 102,  89],
        [104, 102,  90],
        ...,
        [ 81,  77,  74],
        [ 79,  75,  72],
        [ 84,  80,  77]],

       ...,

       [[158, 154, 153],
        [157, 153, 152],
        [157, 153, 152],
        ...,
        [ 21,  21,  19],
        [ 21,  21,  19],
        [ 21,  21,  19]],

       [[158, 154, 153],
        [157, 153, 152],
        [157, 153, 152],
        ...,
        [ 21,  21,  19],
        [ 21,  21,  19],
        [ 21,  21,  19]],

       [[158, 154, 153],
        [157, 153, 152],
        [157, 153, 152],
        ...,
        [ 21,  21,  19],
        [ 21,  21,  19],
        [ 21,  21,  19]]

In [79]:
img3_array

array([[[ 67,  56,  54],
        [ 52,  41,  39],
        [ 76,  65,  63],
        ...,
        [ 62,  39,  33],
        [ 59,  36,  30],
        [ 55,  32,  26]],

       [[ 60,  49,  47],
        [ 61,  50,  48],
        [ 85,  74,  72],
        ...,
        [ 64,  41,  35],
        [ 60,  37,  31],
        [ 57,  34,  28]],

       [[ 54,  43,  41],
        [ 71,  60,  58],
        [ 92,  81,  79],
        ...,
        [ 66,  43,  37],
        [ 63,  40,  34],
        [ 59,  36,  30]],

       ...,

       [[167, 163, 160],
        [151, 147, 144],
        [ 82,  78,  75],
        ...,
        [ 96,  92,  89],
        [ 86,  82,  79],
        [ 93,  89,  86]],

       [[167, 163, 160],
        [150, 146, 143],
        [ 83,  79,  76],
        ...,
        [101,  97,  94],
        [ 89,  85,  82],
        [ 90,  86,  83]],

       [[167, 163, 160],
        [150, 146, 143],
        [ 83,  79,  76],
        ...,
        [109, 105, 102],
        [ 95,  91,  88],
        [ 88,  84,  81]]

In [80]:
img4_array

array([[[108,  98,  96],
        [108,  98,  96],
        [108,  98,  96],
        ...,
        [ 12,  14,  13],
        [ 13,  15,  14],
        [ 14,  16,  15]],

       [[109,  99,  97],
        [108,  98,  96],
        [108,  98,  96],
        ...,
        [ 13,  15,  14],
        [ 16,  18,  17],
        [ 17,  19,  18]],

       [[109,  99,  97],
        [108,  98,  96],
        [107,  97,  95],
        ...,
        [ 16,  18,  17],
        [ 20,  22,  21],
        [ 21,  23,  22]],

       ...,

       [[150, 144, 144],
        [152, 146, 146],
        [153, 147, 147],
        ...,
        [118, 104, 117],
        [118, 104, 117],
        [118, 104, 117]],

       [[148, 142, 142],
        [150, 144, 144],
        [151, 145, 145],
        ...,
        [118, 104, 117],
        [118, 104, 117],
        [118, 104, 117]],

       [[147, 141, 141],
        [148, 142, 142],
        [150, 144, 144],
        ...,
        [118, 104, 117],
        [118, 104, 117],
        [119, 105, 118]]

### 2. Loading image using Opencv

In [91]:
import cv2

In [92]:
img1=cv2.imread("inv1.jpg")

In [93]:
img1

array([[[156, 157, 161],
        [156, 157, 161],
        [156, 157, 161],
        ...,
        [ 50,  62,  80],
        [ 56,  68,  86],
        [ 50,  62,  80]],

       [[157, 158, 162],
        [157, 158, 162],
        [157, 158, 162],
        ...,
        [ 50,  62,  80],
        [ 55,  67,  85],
        [ 50,  62,  80]],

       [[159, 160, 164],
        [159, 160, 164],
        [158, 159, 163],
        ...,
        [ 50,  62,  80],
        [ 56,  68,  86],
        [ 50,  62,  80]],

       ...,

       [[129, 130, 134],
        [137, 138, 142],
        [149, 150, 154],
        ...,
        [ 51,  51, 111],
        [ 44,  44, 104],
        [ 40,  40, 100]],

       [[152, 153, 157],
        [136, 137, 141],
        [135, 136, 140],
        ...,
        [ 50,  51, 109],
        [ 41,  42, 100],
        [ 38,  39,  97]],

       [[147, 148, 152],
        [135, 136, 140],
        [129, 130, 134],
        ...,
        [ 52,  53, 109],
        [ 44,  45, 101],
        [ 42,  43,  99]]

In [94]:
img2=cv2.imread("inv2.jpg")

In [95]:
img2

array([[[ 92, 105, 107],
        [ 91, 104, 106],
        [ 90, 102, 104],
        ...,
        [ 81,  84,  88],
        [ 76,  79,  83],
        [ 75,  80,  83]],

       [[ 91, 104, 106],
        [ 90, 103, 105],
        [ 90, 102, 104],
        ...,
        [ 76,  79,  83],
        [ 73,  76,  80],
        [ 75,  80,  83]],

       [[ 90, 103, 105],
        [ 89, 102, 104],
        [ 90, 102, 104],
        ...,
        [ 74,  77,  81],
        [ 72,  75,  79],
        [ 76,  81,  84]],

       ...,

       [[153, 154, 158],
        [152, 153, 157],
        [152, 153, 157],
        ...,
        [ 19,  21,  21],
        [ 19,  21,  21],
        [ 19,  21,  21]],

       [[153, 154, 158],
        [152, 153, 157],
        [152, 153, 157],
        ...,
        [ 19,  21,  21],
        [ 19,  21,  21],
        [ 19,  21,  21]],

       [[153, 154, 158],
        [152, 153, 157],
        [152, 153, 157],
        ...,
        [ 19,  21,  21],
        [ 19,  21,  21],
        [ 19,  21,  21]]

In [96]:
img3=cv2.imread("inv3.jpg")

In [97]:
img3

array([[[ 54,  56,  67],
        [ 39,  41,  52],
        [ 63,  65,  76],
        ...,
        [ 33,  39,  62],
        [ 30,  36,  59],
        [ 26,  32,  55]],

       [[ 47,  49,  60],
        [ 48,  50,  61],
        [ 72,  74,  85],
        ...,
        [ 35,  41,  64],
        [ 31,  37,  60],
        [ 28,  34,  57]],

       [[ 41,  43,  54],
        [ 58,  60,  71],
        [ 79,  81,  92],
        ...,
        [ 37,  43,  66],
        [ 34,  40,  63],
        [ 30,  36,  59]],

       ...,

       [[160, 163, 167],
        [144, 147, 151],
        [ 75,  78,  82],
        ...,
        [ 89,  92,  96],
        [ 79,  82,  86],
        [ 86,  89,  93]],

       [[160, 163, 167],
        [143, 146, 150],
        [ 76,  79,  83],
        ...,
        [ 94,  97, 101],
        [ 82,  85,  89],
        [ 83,  86,  90]],

       [[160, 163, 167],
        [143, 146, 150],
        [ 76,  79,  83],
        ...,
        [102, 105, 109],
        [ 88,  91,  95],
        [ 81,  84,  88]]